/* AUTO-GENERATED from public/logos/*.png — the slugs that have a bundled
   logo file. StoreLogo only requests /logos/<slug>.png when the slug is
   here, so stores/brands without a bundled file skip straight to the
   favicon tier instead of firing a 404 (QA Jun 2026).
   Regenerate: ls public/logos/*.png | xargs -n1 basename | sed 's/.png//'
*/
export const BUNDLED_LOGOS: ReadonlySet<string> = new Set([
  "3chub",
  "93mobiles",
  "about-you",
  "addmecart",
  "adidas",
  "aliexpress",
  "amazon",
  "ao",
  "argos",
  "asda-george",
  "asos",
  "b-h-photo-video-audio",
  "best-buy",
  "boots",
  "care-to-beauty",
  "currys",
  "debenhams",
  "dell",
  "desertcart-in",
  "dhgate",
  "dick-s-sporting-goods",
  // "ebay" + "healthplus" de-bundled (June 2026): their /logos PNGs are
  // 16x16 placeholders that render as a blurry dot. Removed here so
  // StoreLogo skips the bundled tier and resolves a crisp favicon
  // (ebay.com / healthplusnigeria.com) instead.
  "electronic-express",
  "fashion-nova",
  "flipkart",
  "incredible",
  "jd-williams",
  "jiji",
  "john-lewis-partners",
  "jumia",
  "konga",
  "lookfantastic",
  "lowestrate-shopping",
  "macy-s",
  "marks-electrical",
  "maxfashion",
  "medplus",
  "nfm",
  "noon",
  "nykaa",
  "old-navy",
  "onbuy",
  "poshmark",
  "qvc",
  "shein",
  "slot",
  "smytten",
  "spar",
  "sports-direct-uk",
  "supermart",
  "swarovski-uk",
  "swiss-beauty",
  "syga-india",
  "takealot",
  "temu",
  "threechub",
  "trendyol",
  "ubuy",
  "very",
  "vlebazaar-in",
  "walmart",
]);
