/* AUTO-GENERATED by scripts/fetch-fx-rates.ts from the fx_rates table.
   Do NOT edit by hand. Build-time mirror of the live FX rates so
   country.ts USD_FX stays a static, client-safe, hydration-stable
   constant. The daily FX cron rewrites + commits this. "1 USD = X". */
export const FX_GENERATED: Record<string, number> = {
  "USD": 1,
  "NGN": 1377.17,
  "GBP": 0.7471,
  "EUR": 0.8767,
  "AED": 3.6725,
  "INR": 96.339,
  "ZAR": 16.4614
};
